[package]
name = "newviso-runtime"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
newviso-assets-client.workspace = true
newviso-capabilities.workspace = true
newviso-compat-abi.workspace = true
newviso-config.workspace = true
newviso-content-manager.workspace = true
newviso-core.workspace = true
newviso-host.workspace = true
newviso-input-client.workspace = true
newviso-materials.workspace = true
newviso-model.workspace = true
newviso-platform.workspace = true
newviso-project.workspace = true
newviso-provider-runtime.workspace = true
newviso-render-client.workspace = true
newviso-resource-runtime.workspace = true
newviso-scene.workspace = true
newviso-scripting.workspace = true
newviso-textures.workspace = true
newviso-ui-client.workspace = true
serde.workspace = true
serde_json.workspace = true
